### ISSUE TITLE
tests | visualization test

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#1]
Saving plots can create lot of problems such as not saving, empty images etc.
Check that file exists and greater than 100 kb for a given resolution.

**Comment by vamseeachanta** [comment]
Many polar plots in below location not working. Fix. 

https://github.com/vamseeachanta/assetutilities/blob/2da435abb3559dc03e0e96387a6a4ef641140da3/src/assetutilities/tests/test_data/visualization/results/Plot

**Comment by vamseeachanta** [comment]
@samdansk2 , below is the list
- understand the application. basename: visualization
- Identify tests that run and do not run:
  - https://github.com/vamseeachanta/assetutilities/tree/2da435abb3559dc03e0e96387a6a4ef641140da3/src/assetutilities/tests/test_data/visualization

**Comment by vamseeachanta** [comment]
@samdansk2, please create test_all_yml.py

Starting point is below
https://github.com/vamseeachanta/assetutilities/blob/0742a0ffa0977a74158f8fdd37be2aef2851901b/src/assetutilities/tests/test_data/visualization/test_all_yml.py

command to run an example yml file is below:
python -m assetutilities visualization_polar_ini_step6.yml

**Comment by vamseeachanta** [comment]
@samdansk2 , thank you for the working code. We have 5 failed tests that we need to resolve.

**Comment by vamseeachanta** [comment]
Need to improve the visualization test using AI to identify if the plot has line or otherwise. It should not consider the legend as a plot.

![image](https://github.com/user-attachments/assets/23367115-9d22-4bec-9680-62f3dceaad15)

**Comment by vamseeachanta** [comment]
**Study material:**
https://github.com/vamseeachanta/assetutilities/blob/b2cbe58ce4bf5483ff863adb99ef73ce84aee6d8/docs/sub_visualization/DS-0002-01%20Data%20Visualization%20(DRAFT1).pdf
https://github.com/vamseeachanta/energy/blob/apr_may/it/REF-VIZ-Graphics_Principles_Cheatsheet.pdf
https://github.com/vamseeachanta/energy/blob/apr_may/it/REF-VIZ-Tableau%20Visual%20Guidebook.pdf

**Comment by vamseeachanta** [comment]
fixed a few tests. 2 more tests to fix. See below:
Filename,Status
visualization_polar_normal_lay_forecast.yml,Failed
visualization_polar_plotly.yml,Failed

**Comment by samdansk2** [comment]
@vamseeachanta , Hello sir Good morning , 
After adding image to both XY and Polar plots , some tests are being failed and some output plots have changed . below is the list , you can go through it .

XY Tests :
All tests are facing same error called **Cannot access local variable plt_properties where it is not associated with the value**

Polar_plot Tests : 
All tests are running good , but output plots have changed

**Comment by vamseeachanta** [comment]
We will have to resolve it together...

**Comment by samdansk2** [comment]
Resolved everything (Xy and Polar tests) .
