### ISSUE TITLE
SIMPY | Solve equations

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#22]
- Solve equations using simpy
- Also display equations on screen
- Get all steps documented in a Latex document for printing into PDF

Test data:
- Test1: Solve the simple equations (existing examples from below link)
  - https://github.com/vamseeachanta/assetutilities/blob/f7d7bfea6bc87ec6b96c0fa3bf293f228b234569/docs/sub_math
- Test2: Pressure loss calculation. https://github.com/vamseeachanta/digitalmodel/issues/57

Displaying equation on screen:
  - https://docs.sympy.org/latest/tutorials/intro-tutorial/printing.html

**Comment by samdansk2** [comment]
displaying equations on screen :

ipython console is not opening as described here https://docs.sympy.org/latest/tutorials/intro-tutorial/printing.html

**Comment by vamseeachanta** [comment]
@samdansk2 , first create a test for simple equation and try all the methods above. Let us do this for a simple equation that was used in simpy link above. Can you do this and send me link to the code?

**Comment by samdansk2** [comment]
@vamseeachanta 
I am not getting your point sir
How can we write a test for displaying a single equation ?

**Comment by vamseeachanta** [comment]
@samdansk2 , just a simple function to just display the equations in a terminal?

**Comment by samdansk2** [comment]
@vamseeachanta 
Hello sir good morning , i have researched regarding sympy equation displaying , 
To display math equations visually on screen , there are three ways :
1. Using Sympy in ipython 
2. Using IPython library in Jupyter notebook 
3.. Using Matplotlib in vscode 

--> I have tried all of these ways , from three of this i found **Ipython with Jupyter notebook** and **Matplotlib** are better , gives more visual resulting equations . i am attaching the screenshots of three methods below , please see it .

![ipython ](https://github.com/user-attachments/assets/0eeec7cb-e6fc-4c6e-8d8b-8d4073da2fab)


![Jupyter notebook](https://github.com/user-attachments/assets/6ee427a8-0f25-45da-bc5a-2c1b848939e2)
![Matplotlib](https://github.com/user-attachments/assets/73d168e1-4022-4f91-9fae-9819f46da71a)

**Comment by vamseeachanta** [comment]
Exploring markdown route. See repo folder below:
https://github.com/vamseeachanta/assetutilities/blob/2024aug/docs/sub_latex/markdown

**Comment by vamseeachanta** [comment]
https://github.com/vamseeachanta/assetutilities/blob/574e255e5e13ec955e1ed00f60b027aafbe28783/docs/sub_latex/markdown/sympy_function_2.py
https://github.com/vamseeachanta/assetutilities/blob/574e255e5e13ec955e1ed00f60b027aafbe28783/docs/sub_latex/markdown/sympy_function_2.md
