### ISSUE TITLE
Visualization | Add image to a plot

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#23]
Add image to a plot
Overlaying an image to plot
The image file path, size and location on plot and transperency need to be input.

- Add plantuml file for the process.
- Get the limits for image correctly. If possible, add some guidance notes on how to get it right.

**Comment by vamseeachanta** [comment]
![image](https://github.com/user-attachments/assets/bc5ac838-10b0-42d2-b0e3-af99bfae39fc)
![ini_step6_allowable_wave_height](https://github.com/user-attachments/assets/52f938ed-7dac-48b3-9f12-4888d88b0dbd)

**Comment by vamseeachanta** [comment]
result:
![image](https://github.com/user-attachments/assets/f4705a4b-27ef-45f6-ba8b-24e5f7a8d276)

**Comment by vamseeachanta** [comment]
investigate pillow library
https://pillow.readthedocs.io/en/stable/

https://www.tutorialspoint.com/python_pillow/Python_pillow_merging_images.htm#:~:text=Pillow%20(PIL)%20library%20is%20used,image%20by%20merging%20specific%20bands.

**Comment by vamseeachanta** [comment]
Key steps:
a/ First add an image to matplotlib plot
https://stackoverflow.com/questions/62326845/adding-image-in-matplotlib-plot-creates-blank-output-showing-only-axis
b/ Then start adding a simple plot (X vs Y)

For learning: / combine 2 images by varying the properties (transperency, location of 2nd picture etc.)

**Comment by samdansk2** [comment]
@vamseeachanta 
hello sir , 
tried adding image to matplotlib plot , please see below
 
 -https://github.com/vamseeachanta/assetutilities/blob/8f54fbc30c9935435d7cf14c8360fa4d2b6ad7f6/src/assetutilities/common/add_image_to_plot.py

**Comment by vamseeachanta** [comment]
@samdansk2 , please ensure all the visualization related tests pass. We touched common, xy plots.
We will also touch polar related plots. Hence testing it thoroughly is important.

**Comment by samdansk2** [comment]
polar coordinates : https://mathhints.com/trigonometry/polar-graphs/

**Comment by samdansk2** [comment]
@vamseeachanta 
Hello sir , incorporated the logic you have built in morning into assetutilities visualizaions , 
you can see below :
- https://github.com/vamseeachanta/assetutilities/blob/d8ac51456479c7d0760e5dc9bb6dced5df940c46/src/assetutilities/tests/test_data/visualization/results/Plot/visualization_polar_add_image.png

**Comment by samdansk2** [comment]
Successfully completed the task adding image to both XY and Polar plot. 
Fixed the remaining tests also 👍
