### ISSUE TITLE
Plantuml | VS code integration

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#27]
See subject

**Comment by vamseeachanta** [comment]
{
    "sync.gist": "4f3f54665c291056b894faeea5335662",
    "mssql.connections": [
        {
            "server": "{{put-server-name-here}}",
            "database": "{{put-database-name-here}}",
            "user": "{{put-username-here}}",
            "password": ""
        }
    ],
    "git.confirmSync": false,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "workbench.colorTheme": "Visual Studio Light",
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 2000,
    // PlantUML settings
    "plantuml.exportFormat": "svg",
    "plantuml.exportOutDir": "",
    "plantuml.exportSubFolder": false,
    "plantuml.commandArgs": [],
    "runItOn": {
        "commands": [
            {
                // PlantUML PNG File
                "match": "\\.puml$",
                "isShellCommand": true,
                "cmd": "plantuml -png ${file}",
            },
            {
                // PlantUML SVG File
                "match": "\\.puml$",
                "isShellCommand": true,
                "cmd": "plantuml -svg ${file}",
            },
            // {
            //     // Python Files Black formatter
            //     "match": "\\.py$",
            //     "isShellCommand": true,
            //     "cmd": "python -m black ${file}",
            // },
        ],
        "watchers": [
            {
                "match": "**/*.puml",
                "cmd": "echo 'Changes detected on puml files.'"
            }
        ]
    },
    "extensions.autoUpdate": false,
    "remote.SSH.remotePlatform": {
        "shoerack.lan": "linux"
    },
    "git.ignoreRebaseWarning": true,
    "markdown.marp.enableHtml": true,
    "markdown.marp.exportType": "html",
    "editor.inlineSuggest.enabled": true,
    "editor.renderWhitespace": "all",
    "github.copilot.enable": {
        "*": true,
        "yaml": true,
        "plaintext": true,
        "markdown": true
    },
    "githubPullRequests.createOnPublishBranch": "never",
    "git.mergeEditor": true,
    "security.workspace.trust.untrustedFiles": "open",
    "githubPullRequests.pullBranch": "never",
    "files.encoding": "iso88591",
    "redhat.telemetry.enabled": true,
    "editor.minimap.enabled": false,
    "scm.showChangesSummary": false,
    "pylint.args": [
        "--disable=C"
    ],
    "python.terminal.activateEnvironment": true,
    "[python]": {
        "editor.formatOnType": true,
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": "explicit",
            "source.organizeImports": "always"
        },
    },
    "ruff.organizeImports": "false",
    "black-formatter.args": [],
    "black-formatter.cwd": [],
    "black-formatter.path": [
        "python",
        "-m",
        "black"
    ],
    "black-formatter.interpreter": [],
    "isort.args": [
        "--profile",
        "black"
    ],
    "files.associations": {
        "*.py": "python"
    },
    "editor.formatOnSave": true,
    "editor.fontSize": 18,
}

**Comment by samdansk2** [comment]
@vamseeachanta 
These settings for PlantUML did not worked in my system sir , 
We will discuss in our free pace.
