### ISSUE TITLE
fix library tests

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#4]
Fix all tests on server for seamless integration into future development.
- Add csv with summary of runs and failures
- Helps use only successful .yml files for future
- Helps to fix failures or remove tests if not needed.

**Comment by vamseeachanta** [comment]
@samdansk2 , thank you for helping with the tests.

We fixed a few errors. But more errors occurred downstream and we will fix them further later on.

**Comment by vamseeachanta** [comment]
- keep the folder name as is. No need to clean up
- If run. on screen. Display no.of test passed and failed
- Do the same for digitalmodel

**Comment by samdansk2** [comment]
@vamseeachanta 
Done sir , i have further improved the CSV file for better understanding ,  please see it

**Comment by vamseeachanta** [comment]
The test pipelines should add running of all the yml file tests online and compare against a local run test file.

PS: @getsivakumar , @samdansk2
