### ISSUE TITLE
Develop public library in stages

### ISSUE THREAD

**Issue by vamseeachanta** [vamseeachanta/assetutilities#5]
steps to follow are given below:
https://github.com/vamseeachanta/assetutilities/blob/2024/docs/_public_library.puml

**Comment by vamseeachanta** [comment]
@saiachanta2728 , @samdansk2

**Comment by samdansk2** [comment]
@vamseeachanta 

Hello sir  ,  Created a repository ( https://github.com/samdansk2/LibraryTemplate )

But a small doubt is , In branch1 which yaml file i should read ? can you please tell me .

**Comment by vamseeachanta** [comment]
https://realpython.com/python-modules-packages/
**Naming conventions:**
https://realpython.com/python-pep8/
https://realpython.com/lessons/python-naming-conventions/#transcript

**Comment by vamseeachanta** [comment]
change name to "librarytemplate"

**Comment by vamseeachanta** [comment]
put the below basic functionality in .yml file and read it
- 2 levels of data
- 1 list
- read a 1 .csv file

**Comment by vamseeachanta** [comment]
See some detailed instructions (especially the username/password) to release to pypi here.
https://github.com/vamseeachanta/py_package/blob/improvements/README.md#publishing-to-pypi

**Comment by samdansk2** [comment]
Do I need to change the password sir (or) enter password as " pypi- my account password " in place of password in cmd

**Comment by vamseeachanta** [comment]
I meant your password. On Apr 2, 2024, at 10:53 AM, Samdan Shaik ***@***.***> wrote:﻿
Do I need to change the password sir (or) enter password as " pypi- my account password " in place of password in cmd

**Comment by samdansk2** [comment]
@vamseeachanta 
i have tried the below option :

"Edit > Paste" from the window menu, or enabling " Ctrl+Shift+C/V as Copy/Paste" in "Properties".

even though it is not working sir , i don't know why this is happening ?

**Comment by samdansk2** [comment]
![Screenshot (490)](https://github.com/vamseeachanta/assetutilities/assets/110446718/1fb04f60-510f-47ec-9b33-5b4782075fcf)

**Comment by samdansk2** [comment]
@vamseeachanta 
i am attaching the error below , please see it sir 

![Screenshot (492)](https://github.com/vamseeachanta/assetutilities/assets/110446718/759950ff-3f82-4fbd-ba24-d263e0c04155)
